import type { Lesson } from '$types/lesson';

export const serviceWorkers: Lesson = {
	id: 'sveltekit.advanced-sveltekit.service-workers',
	slug: 'service-workers',
	title: 'Service Workers & Offline Support',
	description: 'Build offline-capable PWAs with SvelteKit service workers, caching strategies, and the $service-worker module.',
	trackId: 'sveltekit',
	moduleId: 'advanced-sveltekit',
	order: 7,
	estimatedMinutes: 20,
	concepts: ['sveltekit.advanced.service-workers', 'sveltekit.advanced.caching-strategies'],
	prerequisites: ['sveltekit.loading.server'],

	content: [
		{
			type: 'text',
			content: `# Service Workers & Offline Support

## Why Service Workers Matter

A service worker is a script that runs in the background, separate from your web page, intercepting network requests and controlling how they are fulfilled. It sits between your application and the network, acting as a programmable proxy. When the network is available, it can pass requests through or serve cached responses. When the network is gone, it can serve cached content, making your application work offline.

For SvelteKit applications, service workers enable:

- **Offline access.** Users can browse previously visited pages without a network connection. For content-heavy sites (documentation, blogs, reference material), this is transformative.
- **Instant repeat visits.** Cached assets load from disk, not the network. Second visits are nearly instantaneous regardless of network speed.
- **Background sync.** Pending mutations (form submissions, data changes) can be queued and sent when the network returns.
- **Push notifications.** The service worker can receive push events even when the app is not open.
- **Progressive Web App (PWA) support.** Service workers are a core requirement for installable PWAs. Combined with a web manifest, they let users install your SvelteKit app on their home screen.

Service workers are not simple. They have a complex lifecycle (install, activate, fetch), caching requires careful strategy, and bugs in service workers can break your entire application in ways that are hard to debug (stale caches serving old code, infinite loops, etc.). SvelteKit simplifies this significantly by providing built-in module access to your app's build artifacts.

## SvelteKit's Service Worker Support

SvelteKit recognizes a special file: \`src/service-worker.ts\` (or \`.js\`). If this file exists, SvelteKit:

1. Bundles it separately from the main application
2. Registers it automatically in the client
3. Provides special modules (\`$service-worker\`) with build-time information
4. Handles the registration lifecycle

You do not need to manually register the service worker or deal with \`navigator.serviceWorker.register()\`. SvelteKit does this for you.

\`\`\`typescript
// src/service-worker.ts
// This file is automatically registered by SvelteKit

import { build, files, version } from '$service-worker';

const CACHE_NAME = \`cache-\${version}\`;

// 'build' contains the hashed app files (JS, CSS)
// 'files' contains the static files from /static
// 'version' is a unique identifier for the current deployment
\`\`\`

## The $service-worker Module

SvelteKit provides three exports from \`$service-worker\`:

**\`build\`** -- An array of URL strings for the files generated by your SvelteKit build. These are the JavaScript chunks, CSS files, and other assets that make up your application. They have hashed filenames, so they are safe to cache indefinitely.

\`\`\`typescript
// Example build contents:
// [
//   '/_app/immutable/entry/app.abc123.js',
//   '/_app/immutable/chunks/index.def456.js',
//   '/_app/immutable/assets/app.ghi789.css'
// ]
\`\`\`

**\`files\`** -- An array of URL strings for the files in your \`static\` directory. These are your images, fonts, favicon, robots.txt, and any other static assets. Unlike build files, these do not have hashed names, so caching strategy needs more care.

\`\`\`typescript
// Example files contents:
// [
//   '/favicon.png',
//   '/robots.txt',
//   '/images/logo.svg',
//   '/fonts/inter.woff2'
// ]
\`\`\`

**\`version\`** -- A string that uniquely identifies the current build. This changes every time you deploy. Use it to namespace your caches so old deployments do not serve stale content.

## Caching Strategies

Different types of content demand different caching approaches. Here are the three fundamental strategies:

### Cache-First (Cache Falling Back to Network)

Check the cache first. If the asset is cached, serve it immediately. If not, fetch from the network, cache the response, and serve it.

**Best for:** Build assets (JS, CSS with hashed filenames), fonts, images that rarely change. These files are immutable -- the filename changes when the content changes.

\`\`\`typescript
async function cacheFirst(request: Request): Promise<Response> {
  const cachedResponse = await caches.match(request);
  if (cachedResponse) {
    return cachedResponse;
  }

  const networkResponse = await fetch(request);
  const cache = await caches.open(CACHE_NAME);
  cache.put(request, networkResponse.clone());
  return networkResponse;
}
\`\`\`

### Network-First (Network Falling Back to Cache)

Try the network first. If the network responds, cache the response and serve it. If the network fails, serve the cached version.

**Best for:** HTML pages, API responses, any content that changes frequently. The user gets the freshest content when online and the last-known-good content when offline.

\`\`\`typescript
async function networkFirst(request: Request): Promise<Response> {
  try {
    const networkResponse = await fetch(request);
    const cache = await caches.open(CACHE_NAME);
    cache.put(request, networkResponse.clone());
    return networkResponse;
  } catch {
    const cachedResponse = await caches.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }
    return new Response('Offline', { status: 503 });
  }
}
\`\`\`

### Stale-While-Revalidate

Serve the cached version immediately (fast), then fetch from the network in the background and update the cache. The next request gets the updated content.

**Best for:** Content that benefits from speed but should eventually update -- avatars, non-critical API data, user profiles.

\`\`\`typescript
async function staleWhileRevalidate(request: Request): Promise<Response> {
  const cache = await caches.open(CACHE_NAME);
  const cachedResponse = await caches.match(request);

  // Fetch from network in background
  const networkPromise = fetch(request).then((networkResponse) => {
    cache.put(request, networkResponse.clone());
    return networkResponse;
  });

  // Return cached immediately if available, otherwise wait for network
  return cachedResponse ?? networkPromise;
}
\`\`\`

## Complete Service Worker Implementation

Here is a production-quality service worker for a SvelteKit app:

\`\`\`typescript
// src/service-worker.ts
import { build, files, version } from '$service-worker';

const CACHE_NAME = \`app-cache-\${version}\`;
const ASSETS = [...build, ...files];

// Install: pre-cache all build assets and static files
self.addEventListener('install', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS))
  );
});

// Activate: delete old caches from previous versions
self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    )
  );
});

// Fetch: serve cached assets, network-first for everything else
self.addEventListener('fetch', (event: FetchEvent) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);

  // Serve build/static assets from cache (cache-first)
  if (ASSETS.includes(url.pathname)) {
    event.respondWith(
      caches.match(event.request).then(
        (cached) => cached ?? fetch(event.request)
      )
    );
    return;
  }

  // For navigation requests, try network first with offline fallback
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .catch(() => caches.match('/offline') ?? new Response('Offline'))
    );
    return;
  }

  // For everything else: network first, fall back to cache
  event.respondWith(
    fetch(event.request)
      .then((response) => {
        const cache = caches.open(CACHE_NAME);
        cache.then((c) => c.put(event.request, response.clone()));
        return response;
      })
      .catch(() => caches.match(event.request))
      .then((response) => response ?? new Response('Offline', { status: 503 }))
  );
});
\`\`\`

## Version-Based Cache Invalidation

The \`version\` from \`$service-worker\` is the key to safe cache management. Each deployment gets a unique version string. The pattern:

1. **Install:** Create a new cache named \`app-cache-\${version}\` and fill it with all current assets
2. **Activate:** Delete all caches whose name does not match the current version
3. **Fetch:** Serve from the current cache

This ensures that after a deployment, the old cache is cleaned up and users get fresh content. Without version-based invalidation, users could be stuck on stale cached content indefinitely.

\`\`\`typescript
// The activate handler cleans up old versions
self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME) // Keep only current
          .map((key) => caches.delete(key))    // Delete all others
      )
    )
  );
});
\`\`\`

## Offline Fallback Page

For a complete offline experience, create a fallback page that is pre-cached and shown when the user navigates to a page that has not been cached:

\`\`\`svelte
<!-- src/routes/offline/+page.svelte -->
<h1>You're Offline</h1>
<p>This page isn't available offline. Please check your internet connection and try again.</p>
<p>Pages you've previously visited may still be available.</p>
<button onclick={() => location.reload()}>Try Again</button>
\`\`\`

Pre-cache the offline page during installation:

\`\`\`typescript
self.addEventListener('install', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll([...ASSETS, '/offline'])
    )
  );
});
\`\`\`

Then serve it as a fallback for failed navigation requests:

\`\`\`typescript
if (event.request.mode === 'navigate') {
  event.respondWith(
    fetch(event.request).catch(async () => {
      const cached = await caches.match('/offline');
      return cached ?? new Response('Offline');
    })
  );
}
\`\`\`

## Debugging Service Workers

Service workers are notoriously tricky to debug. Key tips:

- **Chrome DevTools > Application > Service Workers** shows the current registration, status, and lets you trigger update, unregister, or simulate offline.
- **Cache Storage** (also in Application tab) shows exactly what is cached.
- Use \`skipWaiting()\` during development to immediately activate new service workers instead of waiting for all tabs to close.
- In development, SvelteKit does not register the service worker by default. It only activates in production builds (\`npm run build && npm run preview\`).

\`\`\`typescript
// During development, skip waiting for faster iteration
self.addEventListener('install', (event: ExtendableEvent) => {
  // @ts-ignore
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS))
  );
});
\`\`\``
		},
		{
			type: 'concept-callout',
			content: 'sveltekit.advanced.service-workers'
		},
		{
			type: 'text',
			content: `## Exercise: Build an Offline-Capable App

Create a service worker that pre-caches your SvelteKit app's build assets and static files, serves them cache-first, and provides an offline fallback for uncached navigation requests.

**Your task:**
1. Import \`build\`, \`files\`, and \`version\` from \`$service-worker\`
2. Pre-cache all assets during the install event
3. Delete old caches during the activate event
4. Serve cached assets with a cache-first strategy`
		},
		{
			type: 'checkpoint',
			content: 'cp-1'
		},
		{
			type: 'text',
			content: `## Adding Network-First for Navigation

Enhance your service worker to handle navigation requests (HTML pages) with a network-first strategy, falling back to an offline page when the network is unavailable.

**Task:** Add a fetch event listener that distinguishes between asset requests (cache-first) and navigation requests (network-first with offline fallback).`
		},
		{
			type: 'checkpoint',
			content: 'cp-2'
		},
		{
			type: 'xray-prompt',
			content: `Explain the service worker lifecycle (install, waiting, activate) and why a new service worker does not take control immediately. What problems would arise if SvelteKit automatically activated new service workers without waiting? How does version-based cache naming prevent serving stale assets after a deployment?`
		},
		{
			type: 'text',
			content: `## Summary

SvelteKit makes service workers practical by providing the \`$service-worker\` module with build-time access to your application's assets. The \`build\` array gives you hashed JS/CSS files (safe to cache forever), \`files\` gives you static assets, and \`version\` provides a deployment-unique identifier for cache namespacing. Combine cache-first for immutable assets, network-first for dynamic content, and an offline fallback page for uncached navigations to build a production-quality offline experience. Remember: service workers only activate in production builds, so always test with \`npm run build && npm run preview\`.`
		}
	],

	starterFiles: [
		{
			name: 'service-worker.ts',
			path: '/src/service-worker.ts',
			language: 'typescript',
			content: `// TODO: Import build, files, version from '$service-worker'

// TODO: Create a versioned cache name
// const CACHE_NAME = ...

// TODO: Combine build and files into a single ASSETS array

// TODO: Install event: pre-cache all assets
self.addEventListener('install', (event) => {
  // Open the cache and add all assets
});

// TODO: Activate event: delete old caches
self.addEventListener('activate', (event) => {
  // Get all cache keys and delete ones that don't match CACHE_NAME
});

// TODO: Fetch event: serve from cache or network
self.addEventListener('fetch', (event) => {
  // For GET requests only:
  // - Cached assets: cache-first
  // - Navigation: network-first with offline fallback
});`
		},
		{
			name: 'offline/+page.svelte',
			path: '/src/routes/offline/+page.svelte',
			language: 'svelte',
			content: `<h1>You're Offline</h1>
<p>This page isn't available without an internet connection.</p>
<p>Pages you've previously visited may still be accessible.</p>
<button onclick={() => location.reload()}>Try Again</button>`
		}
	],

	solutionFiles: [
		{
			name: 'service-worker.ts',
			path: '/src/service-worker.ts',
			language: 'typescript',
			content: `import { build, files, version } from '$service-worker';

const CACHE_NAME = \`app-cache-\${version}\`;
const ASSETS = [...build, ...files];

self.addEventListener('install', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll([...ASSETS, '/offline'])
    )
  );
});

self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    )
  );
});

self.addEventListener('fetch', (event: FetchEvent) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);

  if (ASSETS.includes(url.pathname)) {
    event.respondWith(
      caches.match(event.request).then(
        (cached) => cached ?? fetch(event.request)
      )
    );
    return;
  }

  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request).catch(async () => {
        const cached = await caches.match('/offline');
        return cached ?? new Response('Offline', { status: 503 });
      })
    );
    return;
  }

  event.respondWith(
    fetch(event.request)
      .then((response) => {
        const responseClone = response.clone();
        caches.open(CACHE_NAME).then((cache) => {
          cache.put(event.request, responseClone);
        });
        return response;
      })
      .catch(async () => {
        const cached = await caches.match(event.request);
        return cached ?? new Response('Offline', { status: 503 });
      })
  );
});`
		},
		{
			name: 'offline/+page.svelte',
			path: '/src/routes/offline/+page.svelte',
			language: 'svelte',
			content: `<h1>You're Offline</h1>
<p>This page isn't available without an internet connection.</p>
<p>Pages you've previously visited may still be accessible.</p>
<button onclick={() => location.reload()}>Try Again</button>`
		}
	],

	checkpoints: [
		{
			id: 'cp-1',
			description: 'Implement install and activate events with versioned caching',
			validation: {
				type: 'code-pattern',
				config: {
					patterns: [
						{ type: 'contains', value: '$service-worker' },
						{ type: 'contains', value: 'CACHE_NAME' },
						{ type: 'contains', value: 'cache.addAll' }
					]
				}
			},
			hints: [
				'Import `build`, `files`, and `version` from `$service-worker` at the top of the file.',
				'Create `const CACHE_NAME = `app-cache-${version}`` and `const ASSETS = [...build, ...files]`.',
				'In the install listener, use `event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS)))`.'
			],
			conceptsTested: ['sveltekit.advanced.service-workers']
		},
		{
			id: 'cp-2',
			description: 'Add fetch handler with cache-first for assets and network-first for navigation',
			validation: {
				type: 'code-pattern',
				config: {
					patterns: [
						{ type: 'contains', value: 'event.request.mode' },
						{ type: 'contains', value: 'navigate' },
						{ type: 'contains', value: 'caches.match' }
					]
				}
			},
			hints: [
				'Check `event.request.method !== "GET"` and return early for non-GET requests.',
				'For assets in the ASSETS array, use `event.respondWith(caches.match(request).then(cached => cached ?? fetch(request)))`.',
				'For navigation requests (`event.request.mode === "navigate"`), try `fetch` first, and `.catch()` to serve the offline page from cache.'
			],
			conceptsTested: ['sveltekit.advanced.caching-strategies']
		}
	]
};
