import type { LessonData } from '$lib/types';

const lesson: LessonData = {
	meta: {
		id: '19-9',
		title: 'Building Component Libraries: svelte-package',
		phase: 7,
		module: 19,
		lessonIndex: 9
	},
	description: `@sveltejs/package transforms your $lib directory into a publishable npm package. It compiles .svelte files (keeping them as .svelte for downstream compilation), generates .d.ts declaration files, and produces a clean dist/ that npm can consume. The exports field in package.json controls what consumers can import, the svelte field tells bundlers where to find source components, and peerDependencies keeps Svelte itself out of your bundle.

Building a component library is how you share UI across projects or publish to npm. This lesson walks the full workflow: scaffold, develop, package, version, publish.`,
	objectives: [
		'Scaffold a SvelteKit library project with `sv create --template library`',
		'Configure package.json exports, svelte, and peerDependencies fields',
		'Run pnpm package to compile .svelte files and emit .d.ts declarations',
		'Publish to npm with the correct access and version semantics',
		'Consume the published library from another SvelteKit project'
	],
	files: [
		{
			filename: 'App.svelte',
			content: `<script lang="ts">
  type Tab = 'scaffold' | 'structure' | 'exports' | 'publish' | 'wizard';
  let activeTab = $state<Tab>('scaffold');

  // Publish wizard
  type Step = { title: string; description: string; cmd?: string; done: boolean };
  let steps = $state<Step[]>([
    { title: 'Scaffold', description: 'Create a library project', cmd: 'pnpm dlx sv create my-ui --template library --types ts', done: false },
    { title: 'Install', description: 'Install dependencies', cmd: 'cd my-ui && pnpm install', done: false },
    { title: 'Develop', description: 'Build components in src/lib/', done: false },
    { title: 'Test', description: 'Preview components in /routes against src/lib/', cmd: 'pnpm dev', done: false },
    { title: 'svelte-check', description: 'Type check before packaging', cmd: 'pnpm check', done: false },
    { title: 'Package', description: 'Compile src/lib/ into dist/', cmd: 'pnpm package', done: false },
    { title: 'Version', description: 'Bump semver (major/minor/patch)', cmd: 'npm version minor', done: false },
    { title: 'Login', description: 'Authenticate to npm', cmd: 'npm login', done: false },
    { title: 'Publish', description: 'Publish to the registry', cmd: 'npm publish --access public', done: false }
  ]);

  let progress = $derived(
    Math.round((steps.filter((s) => s.done).length / steps.length) * 100)
  );

  function toggleStep(i: number) {
    const next = [...steps];
    next[i] = { ...next[i], done: !next[i].done };
    steps = next;
  }

  const packageJson = \`{
  "name": "@acme/ui",
  "version": "0.1.0",
  "type": "module",
  "license": "MIT",

  "scripts": {
    "dev": "vite dev",
    "build": "vite build && pnpm package",
    "package": "svelte-kit sync && svelte-package && publint",
    "prepublishOnly": "pnpm package",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json"
  },

  "files": ["dist", "!dist/**/*.test.*", "!dist/**/*.spec.*"],
  "svelte": "./dist/index.js",
  "types": "./dist/index.d.ts",

  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "svelte": "./dist/index.js",
      "default": "./dist/index.js"
    },
    "./Button.svelte": {
      "types": "./dist/Button.svelte.d.ts",
      "svelte": "./dist/Button.svelte"
    },
    "./styles.css": "./dist/styles.css"
  },

  "peerDependencies": {
    "svelte": "^5.0.0"
  },

  "devDependencies": {
    "@sveltejs/kit": "^2.0.0",
    "@sveltejs/package": "^2.0.0",
    "svelte": "^5.0.0",
    "publint": "^0.2.0"
  }
}\`;

  const libStructure = \`my-ui/
├── src/
│   ├── lib/                    ← published contents
│   │   ├── Button.svelte
│   │   ├── Card.svelte
│   │   ├── Input.svelte
│   │   ├── styles.css
│   │   └── index.ts            ← public API
│   └── routes/                 ← dev-only preview app
│       └── +page.svelte
├── dist/                       ← generated by svelte-package
│   ├── Button.svelte
│   ├── Button.svelte.d.ts
│   ├── Card.svelte
│   ├── Card.svelte.d.ts
│   ├── index.js
│   └── index.d.ts
├── package.json
└── svelte.config.js\`;

  const indexTs = \`// src/lib/index.ts — public API surface
export { default as Button } from './Button.svelte';
export { default as Card } from './Card.svelte';
export { default as Input } from './Input.svelte';
export { default as Modal } from './Modal.svelte';

// Types too — consumers can import them
export type { ButtonProps } from './Button.svelte';
export type { CardProps } from './Card.svelte';\`;

  const consumerCode = \`// Consumer project — install
$ pnpm add @acme/ui

// In app.css — import library styles
@import '@acme/ui/styles.css';

// In a component — import components
<script lang="ts">
  import { Button, Card } from '@acme/ui';
<\\/script>

<Card>
  <Button variant="primary">Hello from @acme/ui</Button>
</Card>\`;

  const publishFlow = \`# Full publish workflow
$ pnpm check                 # typecheck passes
$ pnpm test                  # unit tests pass
$ pnpm package               # emits dist/
$ pnpm exec publint          # validates package.json + dist/

$ npm version patch          # 0.1.0 -> 0.1.1
                             # creates a git tag v0.1.1

$ npm publish --access public

# CI: publish from GitHub Actions on tag
# .github/workflows/publish.yml
name: publish
on:
  push:
    tags: ['v*']
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: \${{ secrets.NPM_TOKEN }}\`;
</script>

<main>
  <h1>Building Component Libraries</h1>
  <p class="subtitle">@sveltejs/package — from $lib to published npm package</p>

  <nav class="tabs" aria-label="Sections">
    <button class:active={activeTab === 'scaffold'} onclick={() => (activeTab = 'scaffold')}>Scaffold</button>
    <button class:active={activeTab === 'structure'} onclick={() => (activeTab = 'structure')}>Structure</button>
    <button class:active={activeTab === 'exports'} onclick={() => (activeTab = 'exports')}>Exports</button>
    <button class:active={activeTab === 'publish'} onclick={() => (activeTab = 'publish')}>Publish</button>
    <button class:active={activeTab === 'wizard'} onclick={() => (activeTab = 'wizard')}>Wizard</button>
  </nav>

  {#if activeTab === 'scaffold'}
    <section>
      <h2>Scaffold a Library Project</h2>
      <p>The SvelteKit CLI ships a library template that configures <code>svelte-package</code> out of the box.</p>
      <pre><code>$ pnpm dlx sv create my-ui --template library --types ts
$ cd my-ui
$ pnpm install
$ pnpm dev              # runs /routes as a dev preview
$ pnpm package          # compiles src/lib/ into dist/</code></pre>

      <h3>What the template gives you</h3>
      <ul>
        <li><code>src/lib/</code> for components — <strong>anything here is published</strong></li>
        <li><code>src/routes/</code> for a dev-only preview app — <strong>not published</strong></li>
        <li><code>svelte.config.js</code> with package hooks</li>
        <li><code>publint</code> wired in to validate your package.json</li>
      </ul>
    </section>
  {:else if activeTab === 'structure'}
    <section>
      <h2>Project Structure</h2>
      <pre><code>{libStructure}</code></pre>

      <h3>src/lib/index.ts — public API</h3>
      <pre><code>{indexTs}</code></pre>
    </section>
  {:else if activeTab === 'exports'}
    <section>
      <h2>package.json</h2>
      <p>The <code>exports</code> field declares every entry point. Bundlers resolve the <code>svelte</code> condition to get uncompiled source; TypeScript reads the <code>types</code> condition.</p>
      <pre><code>{packageJson}</code></pre>
    </section>
  {:else if activeTab === 'publish'}
    <section>
      <h2>Publishing to npm</h2>
      <pre><code>{publishFlow}</code></pre>

      <h3>Consumer usage</h3>
      <pre><code>{consumerCode}</code></pre>
    </section>
  {:else}
    <section>
      <h2>Publish Wizard</h2>
      <p>Work through the checklist. Click each step to mark it complete.</p>

      <div class="progress-wrap">
        <div class="progress-bar"><div class="progress-fill" style="width: {progress}%"></div></div>
        <span class="progress-num">{progress}%</span>
      </div>

      <div class="steps">
        {#each steps as step, i (step.title)}
          <button class="step-card" class:done={step.done} onclick={() => toggleStep(i)}>
            <span class="step-num">{i + 1}</span>
            <div class="step-body">
              <div class="step-title">{step.title}</div>
              <div class="step-desc">{step.description}</div>
              {#if step.cmd}<code class="step-cmd">{step.cmd}</code>{/if}
            </div>
            <span class="step-check">{step.done ? '✓' : ''}</span>
          </button>
        {/each}
      </div>

      {#if progress === 100}
        <div class="done-banner">Your library is published. Share the npm link.</div>
      {/if}
    </section>
  {/if}
</main>

<style>
  main { max-width: 900px; margin: 0 auto; padding: 2rem; font-family: system-ui, sans-serif; }
  .subtitle { color: #666; margin-bottom: 1.5rem; }

  .tabs { display: flex; gap: 0.35rem; margin-bottom: 1.5rem; border-bottom: 2px solid #e0e0e0; flex-wrap: wrap; }
  .tabs button { padding: 0.55rem 1rem; border: none; background: transparent; border-radius: 6px 6px 0 0; font-weight: 500; cursor: pointer; }
  .tabs button.active { background: #eef4fb; color: #1e40af; }

  section { margin-bottom: 2rem; }
  h2 { margin-top: 0; }

  pre {
    background: #1e1e1e;
    color: #d4d4d4;
    padding: 1rem;
    border-radius: 8px;
    overflow-x: auto;
    font-size: 0.76rem;
    line-height: 1.5;
    max-height: 600px;
  }
  pre code { background: none; padding: 0; }
  code { background: #f0f0f0; padding: 0.1rem 0.3rem; border-radius: 3px; font-size: 0.82rem; }

  ul li { margin: 0.35rem 0; }

  .progress-wrap { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 1rem; }
  .progress-bar { flex: 1; background: #e5e7eb; border-radius: 999px; height: 10px; overflow: hidden; }
  .progress-fill { background: #16a34a; height: 100%; transition: width 200ms; }
  .progress-num { font-weight: 700; font-family: monospace; }

  .steps { display: flex; flex-direction: column; gap: 0.5rem; }
  .step-card {
    display: grid;
    grid-template-columns: 32px 1fr 24px;
    gap: 0.75rem;
    align-items: center;
    padding: 0.8rem 1rem;
    background: #f8f9fa;
    border: 1px solid #e0e0e0;
    border-radius: 10px;
    cursor: pointer;
    text-align: left;
  }
  .step-card.done { background: #dcfce7; border-color: #16a34a; }
  .step-num {
    width: 28px; height: 28px;
    background: #4a90d9;
    color: white;
    border-radius: 50%;
    display: grid;
    place-items: center;
    font-weight: 700;
    font-size: 0.85rem;
  }
  .step-card.done .step-num { background: #16a34a; }
  .step-title { font-weight: 600; font-size: 0.95rem; }
  .step-desc { font-size: 0.82rem; color: #555; }
  .step-cmd {
    display: block;
    margin-top: 0.25rem;
    background: #111;
    color: #9ae6b4;
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
    font-size: 0.75rem;
  }
  .step-check { color: #16a34a; font-size: 1.2rem; font-weight: bold; }

  .done-banner {
    margin-top: 1rem;
    padding: 1rem;
    background: #dcfce7;
    border-radius: 10px;
    text-align: center;
    font-weight: 700;
    color: #166534;
  }
</style>`,
			language: 'svelte'
		}
	]
};

export default lesson;
