import type { Lesson } from '$types/lesson';

export const serverLoad: Lesson = {
	id: 'sveltekit.data-loading.server-load',
	slug: 'server-load',
	title: 'Server Load Functions',
	description: 'Fetch data on the server with +page.server.ts load functions and access secrets safely.',
	trackId: 'sveltekit',
	moduleId: 'data-loading',
	order: 1,
	estimatedMinutes: 15,
	concepts: ['sveltekit.loading.server', 'sveltekit.loading.page-data'],
	prerequisites: ['sveltekit.routing.file-based'],

	content: [
		{
			type: 'text',
			content: `# Server Load Functions

## Why Server Load Functions Are the Default Choice

SvelteKit provides two places to load data: \`+page.server.ts\` (server-only) and \`+page.ts\` (universal). Understanding why server load functions should be your default -- and when to deviate -- is fundamental to building secure, performant SvelteKit applications.

Server load functions run exclusively on the server. They never execute in the browser. This is not just a convenience -- it is a **security boundary**. Code in \`+page.server.ts\` can safely:

- Query databases directly (no API layer needed)
- Use private API keys and secrets
- Access the file system
- Read environment variables from \`$env/static/private\`
- Set and read HTTP-only cookies
- Perform operations that should never be visible in browser DevTools

When a user navigates to a page with a server load function, two different things happen depending on context:

**Initial page load (SSR):** The server runs the load function, gets the data, passes it to the Svelte component, renders HTML, and sends the complete HTML + serialized data to the browser. The browser hydrates the page, using the serialized data without re-running the load function.

**Client-side navigation:** The browser makes a fetch request to a special SvelteKit endpoint (the \`__data.json\` URL). The server runs the load function, serializes the result as JSON, and sends it back. The browser uses this data to render the new page client-side.

In both cases, the load function runs on the server. The difference is the transport mechanism -- HTML embedding vs. JSON fetch.

## The PageServerLoad Type and Its Event Object

The load function receives a rich event object with everything you need to handle the request:

\`\`\`typescript
import type { PageServerLoad } from './$types';

export const load: PageServerLoad = async ({
  params,    // Route parameters -- { slug: 'my-post' }
  url,       // The full URL object -- url.searchParams.get('page')
  cookies,   // Read/write cookies -- cookies.get('session')
  request,   // The raw Request object -- request.headers
  locals,    // Data set by hooks -- locals.user
  fetch,     // Server-side fetch with cookie forwarding
  depends,   // Declare dependencies for invalidation
  parent,    // Access parent layout data (creates waterfall!)
  setHeaders // Set response headers -- setHeaders({ 'Cache-Control': '...' })
}) => {
  // Your data fetching logic
  return { /* data available as props */ };
};
\`\`\`

The \`$types\` import is auto-generated by SvelteKit. It provides type safety based on your route parameters and parent layout data. If your route is \`[slug]\`, \`params.slug\` is typed as \`string\`. If you try to access \`params.id\`, TypeScript will error.

## The Serialization Boundary

Data returned from server load functions must be **serializable**. SvelteKit uses \`devalue\` (not \`JSON.stringify\`) to serialize data, which means you can return:

- Primitives (strings, numbers, booleans, null, undefined)
- Plain objects and arrays
- Dates, Maps, Sets, RegExps, BigInts
- Cyclic references (devalue handles them)

You CANNOT return:
- Functions (how would you send a function over the wire?)
- Class instances (they lose their prototype chain)
- Symbols
- DOM nodes
- Component constructors

This serialization constraint is why \`+page.server.ts\` exists separately from \`+page.ts\`. If you need to return non-serializable data (like a component constructor for dynamic rendering), you must use a universal load function instead.

## Protecting Secrets: The Security Model

The server boundary is absolute. Consider this example:

\`\`\`typescript
// +page.server.ts
import { DATABASE_URL } from '$env/static/private';
import { db } from '$lib/server/database';

export const load: PageServerLoad = async () => {
  const posts = await db.query('SELECT id, title, excerpt FROM posts');

  // DATABASE_URL is used here but NEVER reaches the client.
  // Only the 'posts' array is serialized and sent to the browser.
  return { posts };
};
\`\`\`

SvelteKit enforces this at multiple levels:
1. **Import guards:** Importing from \`$env/static/private\` in client-side code causes a build error.
2. **File convention:** \`+page.server.ts\` files are excluded from the client bundle entirely. Vite never processes them for the browser.
3. **Serialization:** Only the return value crosses the wire -- not the module's imports, variables, or intermediate computations.

## Performance Considerations and Caching

Server load functions run on every request by default. For data that changes infrequently, you can use \`setHeaders\` to add cache headers:

\`\`\`typescript
export const load: PageServerLoad = async ({ setHeaders }) => {
  setHeaders({ 'Cache-Control': 'max-age=60' });
  const posts = await fetchPosts();
  return { posts };
};
\`\`\`

During client-side navigation, SvelteKit respects these cache headers for the \`__data.json\` requests. This means setting \`max-age=60\` effectively caches the load function result for 60 seconds on the client.

For more granular control, use the \`depends()\` + \`invalidate()\` system (covered in the invalidation lesson). This lets you programmatically decide when data should be refetched.

## Decision Framework: Server Load vs. Universal Load

Use **server load** (\`+page.server.ts\`) when:
- You access databases, file systems, or private APIs
- You use secrets, API keys, or private environment variables
- You want to keep implementation details off the client
- Your data is fully serializable

Use **universal load** (\`+page.ts\`) when:
- You need to return non-serializable data (component constructors, functions)
- You are fetching from a public API and want the browser to make the request directly on navigation
- You need to run logic in both SSR and CSR contexts

When in doubt, start with server load. It is more secure and you can always migrate to universal load later if needed.`
		},
		{
			type: 'concept-callout',
			content: 'sveltekit.loading.server'
		},
		{
			type: 'text',
			content: `## Your First Load Function

Look at the starter code -- there's a \`+page.server.ts\` that needs to return data and a \`+page.svelte\` that will display it.

**Your task:** Write a load function that returns a list of posts.`
		},
		{
			type: 'checkpoint',
			content: 'cp-1'
		},
		{
			type: 'text',
			content: `## Accessing the Data in Your Page

The data returned from your load function is available as the \`data\` prop in your page component. In Svelte 5, you destructure it from \`$props()\`.

**Task:** Display the posts from the load function in the page component.`
		},
		{
			type: 'checkpoint',
			content: 'cp-2'
		},
		{
			type: 'text',
			content: `## Using Server-Only Resources

Since \`+page.server.ts\` only runs on the server, you can safely use environment variables, database connections, and other secrets without them leaking to the client.

**Task:** Use a simulated API key in the load function to demonstrate server-only access.`
		},
		{
			type: 'checkpoint',
			content: 'cp-3'
		}
	],

	starterFiles: [
		{
			name: '+page.server.ts',
			path: '/+page.server.ts',
			language: 'typescript',
			content: `import type { PageServerLoad } from './$types';

// TODO: Export a load function that returns { posts: [...] }

export const load: PageServerLoad = async () => {
  return {};
};`
		},
		{
			name: '+page.svelte',
			path: '/+page.svelte',
			language: 'svelte',
			content: `<script lang="ts">
  let { data } = $props();
</script>

<h1>Blog Posts</h1>

<!-- TODO: Display the posts from data -->`
		}
	],

	solutionFiles: [
		{
			name: '+page.server.ts',
			path: '/+page.server.ts',
			language: 'typescript',
			content: `import type { PageServerLoad } from './$types';

const API_KEY = 'sk-secret-key-123'; // Safe! Only on server

export const load: PageServerLoad = async () => {
  // Simulate fetching posts from a database
  const posts = [
    { id: 1, title: 'Getting Started with SvelteKit', excerpt: 'Learn the basics...' },
    { id: 2, title: 'Server Load Functions', excerpt: 'Fetch data safely...' },
    { id: 3, title: 'Form Actions', excerpt: 'Handle form submissions...' }
  ];

  console.log('Fetching with API key:', API_KEY); // Only logs on server

  return { posts };
};`
		},
		{
			name: '+page.svelte',
			path: '/+page.svelte',
			language: 'svelte',
			content: `<script lang="ts">
  let { data } = $props();
</script>

<h1>Blog Posts</h1>

<ul>
  {#each data.posts as post}
    <li>
      <h2>{post.title}</h2>
      <p>{post.excerpt}</p>
    </li>
  {/each}
</ul>`
		}
	],

	checkpoints: [
		{
			id: 'cp-1',
			description: 'Create a load function that returns posts data',
			validation: {
				type: 'code-pattern',
				config: {
					patterns: [
						{ type: 'contains', value: 'return' },
						{ type: 'contains', value: 'posts' }
					]
				}
			},
			hints: [
				'The load function should return an object with your data.',
				'Create an array of post objects with properties like `id`, `title`, `excerpt`.',
				'Return `{ posts }` from the load function.'
			],
			conceptsTested: ['sveltekit.loading.server']
		},
		{
			id: 'cp-2',
			description: 'Display the posts in the page component',
			validation: {
				type: 'code-pattern',
				config: {
					patterns: [
						{ type: 'contains', value: 'data.posts' },
						{ type: 'contains', value: '{#each' }
					]
				}
			},
			hints: [
				'Access the data via `data.posts` in your template.',
				'Use `{#each data.posts as post}` to iterate over the posts.',
				'Display each post\'s title and excerpt inside the each block.'
			],
			conceptsTested: ['sveltekit.loading.page-data']
		},
		{
			id: 'cp-3',
			description: 'Use server-only secrets in the load function',
			validation: {
				type: 'code-pattern',
				config: {
					patterns: [{ type: 'regex', value: '(API_KEY|secret|private)' }]
				}
			},
			hints: [
				'Define a constant like `const API_KEY = \'...\';` in your server file.',
				'This value never reaches the client because `+page.server.ts` only runs on the server.',
				'You can safely use database credentials, API keys, etc. in server load functions.'
			],
			conceptsTested: ['sveltekit.loading.server']
		}
	]
};
