import type { Lesson } from '$types/lesson';

export const componentTesting: Lesson = {
	id: 'sveltekit.testing.component-testing',
	slug: 'component-testing',
	title: 'Testing Svelte Components',
	description: 'Write robust component tests with Vitest and @testing-library/svelte for Svelte 5 components in SvelteKit.',
	trackId: 'sveltekit',
	moduleId: 'testing',
	order: 1,
	estimatedMinutes: 25,
	concepts: ['sveltekit.testing.component-testing', 'sveltekit.testing.vitest-setup'],
	prerequisites: ['sveltekit.loading.server'],

	content: [
		{
			type: 'text',
			content: `# Testing Svelte Components

## Why Component Testing Matters

You have built a Svelte 5 component. It renders correctly when you look at it in the browser. You click around, everything works. Ship it?

Not yet. Manual testing catches what you think to test. It misses everything else. It does not catch regressions -- when a change in one part of the codebase breaks another. It does not catch edge cases -- when the component receives unexpected props, when a network request fails, when the user double-clicks a submit button.

Component testing automates the verification of your UI. You write code that renders a component, simulates user interactions, and asserts that the output matches expectations. These tests run in milliseconds, can be executed on every commit, and catch regressions before they reach users.

For SvelteKit applications, component testing verifies that:
- Components render correctly with given props
- User interactions (clicks, typing, form submissions) produce the expected results
- Reactive state updates ($state, $derived) propagate correctly to the DOM
- Components integrate properly with SvelteKit's context (navigation, page data)

## Why Testing Svelte 5 Is Different from Testing React

If you are coming from the React ecosystem, the mechanics of component testing may feel familiar -- you render a component, query the DOM, fire events, and assert on output. But Svelte 5 is architecturally different from React in ways that directly affect how tests work, what you can test, and what pitfalls you will encounter.

**No virtual DOM.** React maintains a virtual DOM tree in memory and reconciles it with the real DOM on every render cycle. When you call \`setState\` or update a hook, React re-executes the entire component function, diffs the old and new virtual trees, and patches the real DOM. Svelte 5 does none of this. The Svelte compiler analyzes your component at build time and generates imperative JavaScript code that surgically updates only the specific DOM nodes that depend on changed state. There is no diffing phase, no reconciliation, and no concept of "re-rendering" the way React defines it. This means that when you fire an event in a test, the DOM update is not a re-render of the whole component -- it is a targeted mutation of the affected elements.

**Compiled output is what runs.** When you test a React component, the code that runs in the test is essentially the same JSX function you wrote, executed by React's runtime. When you test a Svelte component, the code that runs is the *compiled output* -- JavaScript generated by the Svelte compiler from your \`.svelte\` file. This is why Vitest must be configured with the Svelte plugin: it needs to compile \`.svelte\` files into JavaScript before executing tests. The compiled code contains Svelte's fine-grained reactivity system, which schedules DOM updates asynchronously in microtasks. This is why you often need \`await\` or \`waitFor\` after firing events -- the DOM is not updated synchronously.

**Runes are compiler directives, not runtime APIs.** React hooks (\`useState\`, \`useEffect\`, \`useMemo\`) are runtime functions that execute on every render. Svelte 5 runes (\`$state\`, \`$derived\`, \`$effect\`) are compile-time directives that the compiler transforms into reactive signals. You cannot call \`$state()\` in a test file -- it only works inside \`.svelte\` or \`.svelte.ts\` files that the compiler processes. This has implications for how you set up test state: you cannot reach into a component's internals and directly mutate its \`$state\` variables from a test. Instead, you must interact with the component through its public interface -- props, events, and the rendered DOM.

**No \`act()\` wrapper needed.** In React Testing Library, you wrap interactions in \`act()\` to ensure state updates and effects are flushed. Svelte does not need this pattern. However, Svelte's asynchronous update batching means you still need to wait for DOM changes -- \`await fireEvent.click(button)\` or \`await waitFor(...)\` handles this.

## Setting Up Vitest for Svelte 5

SvelteKit projects created with \`npx sv create\` can include Vitest automatically. If you need to add it manually:

\`\`\`bash
npm install -D vitest @testing-library/svelte @testing-library/jest-dom jsdom
\`\`\`

### Vitest Configuration Deep Dive

Configure Vitest in your \`vite.config.ts\` (or a separate \`vitest.config.ts\` if you prefer to decouple test configuration from build configuration):

\`\`\`typescript
// vite.config.ts
import { defineConfig } from 'vitest/config';
import { sveltekit } from '@sveltejs/kit/vite';

export default defineConfig({
  plugins: [sveltekit()],
  test: {
    include: ['src/**/*.{test,spec}.{js,ts}'],
    environment: 'jsdom',
    setupFiles: ['./src/tests/setup.ts'],
    globals: true,              // optional: use describe/test/expect without imports
    restoreMocks: true,         // automatically restore mocks between tests
    css: true                   // process CSS (useful if components use :global or CSS variables)
  }
});
\`\`\`

The \`sveltekit()\` plugin is essential. It registers the Svelte compiler as a Vite transform, so when Vitest encounters an \`import Counter from './Counter.svelte'\`, the \`.svelte\` file is compiled to JavaScript before the test runs. Without this plugin, Vitest would try to parse the \`.svelte\` file as plain JavaScript and fail.

**\`jsdom\` vs \`happy-dom\`:** The \`environment\` option determines which DOM implementation runs in Node.js. \`jsdom\` is the most complete and widely used -- it supports nearly all Web APIs, handles edge cases well, and is the default recommendation. \`happy-dom\` is an alternative that is significantly faster (often 2-3x) but implements fewer APIs. If your components use advanced APIs like \`IntersectionObserver\`, \`ResizeObserver\`, \`MutationObserver\`, or complex CSS features, \`jsdom\` is safer. If your components are straightforward and you prioritize test speed, \`happy-dom\` works well:

\`\`\`typescript
// For happy-dom instead of jsdom:
// npm install -D happy-dom
test: {
  environment: 'happy-dom'
}
\`\`\`

You can also set the environment per-file using a magic comment at the top of the test file:

\`\`\`typescript
// @vitest-environment happy-dom
import { render, screen } from '@testing-library/svelte';
\`\`\`

Create the setup file to extend Vitest with DOM matchers:

\`\`\`typescript
// src/tests/setup.ts
import '@testing-library/jest-dom/vitest';
\`\`\`

This adds matchers like \`toBeInTheDocument()\`, \`toHaveTextContent()\`, \`toBeVisible()\`, and \`toBeDisabled()\` to your test assertions. You can also add global mocks here, such as mocking \`window.matchMedia\` or \`IntersectionObserver\`:

\`\`\`typescript
// src/tests/setup.ts
import '@testing-library/jest-dom/vitest';

// Mock matchMedia for components using media queries
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false
  })
});
\`\`\`

## The Testing Library Philosophy

\`@testing-library/svelte\` follows a principle: **test the component the way a user would use it.** This means:

- Query elements by their accessible role, label text, or visible text -- not by CSS classes, IDs, or component internals
- Interact with elements through user-facing APIs (click, type, select) -- not by directly mutating state
- Assert on visible output -- not on internal state variables

This approach produces tests that are resilient to refactoring. If you rename a CSS class, restructure your markup, or change internal state names, the tests still pass as long as the user-facing behavior is unchanged.

## render() -- Mounting Components

The \`render\` function mounts a Svelte component into a test DOM:

\`\`\`typescript
import { render } from '@testing-library/svelte';
import Counter from './Counter.svelte';

test('renders with initial count', () => {
  const { getByText } = render(Counter, { props: { initialCount: 5 } });
  expect(getByText('Count: 5')).toBeInTheDocument();
});
\`\`\`

\`render\` returns an object with query functions bound to the rendered component's container. You can also use the global \`screen\` object, which queries the entire document:

\`\`\`typescript
import { render, screen } from '@testing-library/svelte';
import Counter from './Counter.svelte';

test('renders with initial count', () => {
  render(Counter, { props: { initialCount: 5 } });
  expect(screen.getByText('Count: 5')).toBeInTheDocument();
});
\`\`\`

For Svelte 5 components that use \`$props()\`, pass props in the \`props\` key:

\`\`\`typescript
// Component: let { name, age } = $props();
render(UserCard, { props: { name: 'Alice', age: 30 } });
\`\`\`

## Screen Queries -- Finding Elements

Testing Library provides several query types, each with different behavior when the element is not found:

**\`getBy*\`** -- Returns the element or throws immediately if not found. Use for elements that should be present.
\`\`\`typescript
screen.getByRole('button', { name: 'Submit' });  // Throws if missing
screen.getByText('Welcome');                       // Throws if missing
screen.getByLabelText('Email');                    // Throws if missing
\`\`\`

**\`queryBy*\`** -- Returns the element or \`null\` if not found. Use when asserting an element is NOT present.
\`\`\`typescript
expect(screen.queryByText('Error')).not.toBeInTheDocument();
\`\`\`

**\`findBy*\`** -- Returns a Promise that resolves when the element appears (with a timeout). Use for elements that appear asynchronously.
\`\`\`typescript
const message = await screen.findByText('Data loaded');
expect(message).toBeInTheDocument();
\`\`\`

The query suffix determines what you search by:

| Suffix | Searches by | Example |
|---|---|---|
| \`ByRole\` | ARIA role | \`getByRole('button')\` |
| \`ByText\` | Visible text content | \`getByText('Submit')\` |
| \`ByLabelText\` | Form label text | \`getByLabelText('Email')\` |
| \`ByPlaceholderText\` | Input placeholder | \`getByPlaceholderText('Search...')\` |
| \`ByAltText\` | Image alt text | \`getByAltText('Profile photo')\` |
| \`ByTestId\` | data-testid attribute | \`getByTestId('custom-element')\` |

**Priority order:** Prefer \`ByRole\` > \`ByLabelText\` > \`ByText\` > \`ByTestId\`. The more accessible the query, the better the test.

## fireEvent and User Interactions

\`fireEvent\` dispatches DOM events to simulate user interaction:

\`\`\`typescript
import { render, screen, fireEvent } from '@testing-library/svelte';
import Counter from './Counter.svelte';

test('increments count on button click', async () => {
  render(Counter, { props: { initialCount: 0 } });

  const button = screen.getByRole('button', { name: 'Increment' });
  await fireEvent.click(button);

  expect(screen.getByText('Count: 1')).toBeInTheDocument();
});
\`\`\`

Common events:

\`\`\`typescript
await fireEvent.click(element);                    // Mouse click
await fireEvent.input(input, { target: { value: 'hello' } }); // Input change
await fireEvent.submit(form);                      // Form submission
await fireEvent.keyDown(element, { key: 'Enter' }); // Keyboard
await fireEvent.change(select, { target: { value: 'option2' } }); // Select
\`\`\`

**Important for Svelte 5:** After firing events that trigger reactive state updates, the DOM updates asynchronously. Use \`await\` with \`fireEvent\` or use \`waitFor\` to wait for the DOM to reflect changes:

\`\`\`typescript
import { waitFor } from '@testing-library/svelte';

await fireEvent.click(button);
await waitFor(() => {
  expect(screen.getByText('Count: 1')).toBeInTheDocument();
});
\`\`\`

## Testing $state Reactivity

Svelte 5's \`$state\` rune creates fine-grained reactive signals. When testing components that use \`$state\`, you cannot directly read or mutate the state variable from outside the component. Instead, you verify state changes through their DOM effects -- the text that changes, the class that toggles, the element that appears or disappears.

\`\`\`typescript
test('toggle button switches between on and off', async () => {
  render(ToggleSwitch);

  const button = screen.getByRole('button');
  expect(button).toHaveTextContent('Off');

  await fireEvent.click(button);
  await waitFor(() => {
    expect(button).toHaveTextContent('On');
  });

  await fireEvent.click(button);
  await waitFor(() => {
    expect(button).toHaveTextContent('Off');
  });
});
\`\`\`

When a component exposes state through callback props, you can observe state changes indirectly:

\`\`\`typescript
test('tracks internal state changes via callback', async () => {
  const stateChanges: boolean[] = [];
  render(ToggleSwitch, {
    props: { ontoggle: (val: boolean) => stateChanges.push(val) }
  });

  await fireEvent.click(screen.getByRole('button'));
  await fireEvent.click(screen.getByRole('button'));

  expect(stateChanges).toEqual([true, false]);
});
\`\`\`

### The tick() Function for Synchronous Flush

Sometimes \`waitFor\` is more ceremony than you need. Svelte exports a \`tick()\` function that returns a promise which resolves after all pending state changes have been applied to the DOM. This is lighter-weight than \`waitFor\` when you know exactly one update cycle is needed:

\`\`\`typescript
import { tick } from 'svelte';

test('count updates after tick', async () => {
  render(Counter);
  await fireEvent.click(screen.getByRole('button', { name: 'Increment' }));
  await tick();
  expect(screen.getByText('Count: 1')).toBeInTheDocument();
});
\`\`\`

Use \`tick()\` when the update is deterministic and immediate. Use \`waitFor()\` when the update depends on asynchronous operations (fetch, timers, transitions) where you cannot predict exactly when the DOM will change.

## Testing $derived Computations

\`$derived\` values are computed from other reactive state. To test them, change the inputs (via user interaction or prop changes) and assert that the derived output appears correctly in the DOM:

\`\`\`typescript
test('derived state updates when input changes', async () => {
  render(TemperatureConverter);

  const celsiusInput = screen.getByLabelText('Celsius');
  await fireEvent.input(celsiusInput, { target: { value: '100' } });

  await waitFor(() => {
    expect(screen.getByText('212°F')).toBeInTheDocument();
  });
});
\`\`\`

For a component that computes a filtered list from a search query:

\`\`\`typescript
test('filter updates derived list', async () => {
  render(SearchableList, {
    props: { items: ['Apple', 'Banana', 'Cherry', 'Avocado'] }
  });

  const search = screen.getByRole('searchbox');
  await fireEvent.input(search, { target: { value: 'a' } });

  await waitFor(() => {
    expect(screen.getByText('Apple')).toBeInTheDocument();
    expect(screen.getByText('Avocado')).toBeInTheDocument();
    expect(screen.queryByText('Cherry')).not.toBeInTheDocument();
  });
});
\`\`\`

The key insight is that you never test \`$derived\` directly. You test its visible output. If the derived value drives a CSS class, assert on the class. If it drives rendered text, assert on the text. If it drives conditional rendering, assert on the presence or absence of elements.

## Testing $effect Side Effects

\`$effect\` runs side effects when reactive dependencies change. Testing effects requires asserting on the side effect's observable outcome -- a DOM change, a function call, a network request, or a stored value.

\`\`\`typescript
test('effect runs after state change', async () => {
  render(AutoSaveForm);

  const input = screen.getByLabelText('Title');
  await fireEvent.input(input, { target: { value: 'New title' } });

  // Wait for the $effect that shows a "Saved" indicator
  const saved = await screen.findByText('Saved');
  expect(saved).toBeInTheDocument();
});
\`\`\`

For effects that call external functions, use Vitest mocks to verify the effect ran:

\`\`\`typescript
test('effect calls analytics on page change', async () => {
  const trackPage = vi.fn();
  render(PageTracker, { props: { trackPage } });

  // Simulate a page change that triggers the effect
  await fireEvent.click(screen.getByRole('link', { name: 'About' }));

  await waitFor(() => {
    expect(trackPage).toHaveBeenCalledWith('/about');
  });
});
\`\`\`

**Testing effect cleanup:** When an \`$effect\` returns a cleanup function, the cleanup runs before the effect re-runs and when the component is destroyed. To verify cleanup behavior, unmount the component:

\`\`\`typescript
import { render, cleanup } from '@testing-library/svelte';

test('effect cleanup runs on unmount', () => {
  const unsubscribe = vi.fn();
  const subscribe = vi.fn(() => unsubscribe);

  render(Subscriber, { props: { subscribe } });

  expect(subscribe).toHaveBeenCalledOnce();
  expect(unsubscribe).not.toHaveBeenCalled();

  cleanup();  // unmounts all rendered components

  expect(unsubscribe).toHaveBeenCalledOnce();
});
\`\`\`

## Testing Component Props and Events

Test that components respond correctly to different prop values:

\`\`\`typescript
test('renders disabled state', () => {
  render(Button, { props: { disabled: true, label: 'Submit' } });
  expect(screen.getByRole('button', { name: 'Submit' })).toBeDisabled();
});

test('renders enabled state', () => {
  render(Button, { props: { disabled: false, label: 'Submit' } });
  expect(screen.getByRole('button', { name: 'Submit' })).not.toBeDisabled();
});
\`\`\`

For testing callback props (the Svelte 5 pattern of passing functions as props instead of dispatching events):

\`\`\`typescript
import { vi } from 'vitest';

test('calls onclick callback when clicked', async () => {
  const handleClick = vi.fn();
  render(Button, { props: { label: 'Click me', onclick: handleClick } });

  await fireEvent.click(screen.getByRole('button', { name: 'Click me' }));

  expect(handleClick).toHaveBeenCalledOnce();
});
\`\`\`

## Testing with Context (setContext / getContext)

Some Svelte components rely on Svelte's \`getContext\` / \`setContext\`. This is common for theme providers, authentication state, feature flags, and other cross-cutting concerns. There are two primary approaches to providing context in tests.

**Approach 1: Wrapper component.** Create a dedicated test wrapper that calls \`setContext\` before rendering the component under test:

\`\`\`typescript
// TestWrapper.svelte:
// <script>
//   import { setContext } from 'svelte';
//   let { children, contextValue } = $props();
//   setContext('myKey', contextValue);
// </script>
// {@render children()}

import TestWrapper from './TestWrapper.svelte';

test('component uses context', () => {
  render(TestWrapper, {
    props: {
      contextValue: { user: { name: 'Alice' } },
    }
  });
});
\`\`\`

**Approach 2: Mock \`getContext\` directly.** This avoids creating wrapper components:

\`\`\`typescript
vi.mock('svelte', async () => {
  const actual = await vi.importActual('svelte');
  return {
    ...actual,
    getContext: vi.fn((key: string) => {
      if (key === 'user') return { name: 'Alice', role: 'admin' };
      if (key === 'theme') return { mode: 'dark', accent: '#3b82f6' };
      return undefined;
    })
  };
});

test('displays user name from context', () => {
  render(UserProfile);
  expect(screen.getByText('Alice')).toBeInTheDocument();
});
\`\`\`

When mocking \`getContext\`, be careful to spread \`actual\` so you do not accidentally remove other Svelte runtime functions (\`onMount\`, \`tick\`, \`mount\`, etc.) that the component or testing library depends on. Also remember to call \`vi.restoreAllMocks()\` in \`afterEach\` (or set \`restoreMocks: true\` in your Vitest config) so the mock does not leak into other test files.

## Snapshot Testing for Component Output

Vitest supports snapshot testing, which captures the rendered HTML of a component and compares it against a stored reference. This is useful for detecting unintended changes to component output:

\`\`\`typescript
test('matches snapshot', () => {
  const { container } = render(UserCard, {
    props: { name: 'Alice', role: 'Admin' }
  });
  expect(container.innerHTML).toMatchSnapshot();
});
\`\`\`

The first time this test runs, Vitest creates a snapshot file (a \`.snap\` file next to your test). On subsequent runs, it compares the current output against the stored snapshot. If the HTML changes, the test fails and shows you the diff. You can update snapshots with \`npx vitest --update\` or press \`u\` in watch mode.

**Inline snapshots** store the expected output directly in the test file:

\`\`\`typescript
test('matches inline snapshot', () => {
  const { container } = render(Badge, { props: { label: 'New' } });
  expect(container.innerHTML).toMatchInlineSnapshot(
    \`"<span class=\\"badge\\">New</span>"\`
  );
});
\`\`\`

**When to use snapshots:** Snapshots work well for small, stable components where you want to catch unintended markup changes. They work poorly for large components or components with dynamic content (timestamps, random IDs), because the snapshots become noisy and developers start blindly updating them. Prefer explicit assertions (\`toHaveTextContent\`, \`toBeInTheDocument\`) for most tests, and reserve snapshots for verifying specific HTML structure when structure matters.

## Mocking $app/navigation and $app/state

SvelteKit modules like \`$app/navigation\` and \`$app/state\` are not available in the test environment. You must mock them:

\`\`\`typescript
import { vi } from 'vitest';

// Mock $app/navigation
vi.mock('$app/navigation', () => ({
  goto: vi.fn(),
  invalidate: vi.fn(),
  invalidateAll: vi.fn(),
  preloadData: vi.fn(),
  preloadCode: vi.fn(),
  pushState: vi.fn(),
  replaceState: vi.fn()
}));

// Mock $app/state
vi.mock('$app/state', () => ({
  page: {
    url: new URL('http://localhost/test'),
    params: {},
    route: { id: '/test' },
    status: 200,
    error: null,
    data: {},
    state: {}
  }
}));
\`\`\`

Then in your tests, you can assert that navigation functions were called:

\`\`\`typescript
import { goto } from '$app/navigation';

test('navigates to dashboard after login', async () => {
  render(LoginForm);

  await fireEvent.input(screen.getByLabelText('Email'), {
    target: { value: 'user@example.com' }
  });
  await fireEvent.input(screen.getByLabelText('Password'), {
    target: { value: 'password123' }
  });
  await fireEvent.click(screen.getByRole('button', { name: 'Log In' }));

  expect(goto).toHaveBeenCalledWith('/dashboard');
});
\`\`\`

## Integration Testing: Form Submission to UI Update

Component tests can go beyond unit-level assertions. Integration-style component tests verify a full user flow within a single component or a small component tree. A common pattern is testing form submission that triggers an API call and updates the UI:

\`\`\`typescript
test('submits form, calls API, and shows success message', async () => {
  // Mock the fetch call the component makes
  global.fetch = vi.fn().mockResolvedValue({
    ok: true,
    json: () => Promise.resolve({ id: 1, name: 'New Item' })
  });

  render(CreateItemForm);

  await fireEvent.input(screen.getByLabelText('Item name'), {
    target: { value: 'New Item' }
  });
  await fireEvent.click(screen.getByRole('button', { name: 'Create' }));

  // Wait for the async API call and subsequent UI update
  const success = await screen.findByText('Item created successfully');
  expect(success).toBeInTheDocument();

  expect(global.fetch).toHaveBeenCalledWith('/api/items', expect.objectContaining({
    method: 'POST',
    body: JSON.stringify({ name: 'New Item' })
  }));
});

test('shows error message when API call fails', async () => {
  global.fetch = vi.fn().mockResolvedValue({
    ok: false,
    status: 500,
    json: () => Promise.resolve({ error: 'Server error' })
  });

  render(CreateItemForm);

  await fireEvent.input(screen.getByLabelText('Item name'), {
    target: { value: 'New Item' }
  });
  await fireEvent.click(screen.getByRole('button', { name: 'Create' }));

  const error = await screen.findByText('Server error');
  expect(error).toBeInTheDocument();
});
\`\`\`

This pattern verifies the complete user journey: interaction, network request, and resulting UI change. It catches bugs that unit tests on individual functions would miss, such as the component not awaiting the fetch, not handling errors, or not clearing the form after success.

## Common Pitfalls

**Forgetting to await async updates.** This is the most common mistake. Svelte 5's reactivity is asynchronous. After \`fireEvent.click(button)\`, the DOM is not updated synchronously. Always use \`await fireEvent\`, \`await tick()\`, or \`await waitFor()\`:

\`\`\`typescript
// WRONG: assertion runs before DOM updates
fireEvent.click(button);
expect(screen.getByText('Count: 1')).toBeInTheDocument(); // May fail

// CORRECT: wait for update
await fireEvent.click(button);
await waitFor(() => {
  expect(screen.getByText('Count: 1')).toBeInTheDocument();
});
\`\`\`

**Not cleaning up between tests.** Testing Library's \`cleanup\` function unmounts components rendered during a test. It runs automatically after each test when using the default setup, but if you configure Vitest with \`globals: false\` or a custom setup, you may need to call it manually. Leaking mounted components between tests causes false positives and confusing failures.

**Querying too soon for async content.** If a component fetches data on mount and renders loading/content states, use \`findByText\` (which polls) instead of \`getByText\` (which asserts immediately):

\`\`\`typescript
// WRONG: component is still loading
render(UserProfile);
expect(screen.getByText('Alice')).toBeInTheDocument(); // Throws

// CORRECT: wait for content to appear
render(UserProfile);
expect(await screen.findByText('Alice')).toBeInTheDocument();
\`\`\`

**Testing implementation details.** Avoid asserting on CSS classes, internal variable names, or component instance properties. These are implementation details that can change without affecting user behavior. Test what the user sees and interacts with.

## Structuring Test Files

Place test files alongside the components they test:

\`\`\`
src/lib/components/
  Counter.svelte
  Counter.test.ts
  Button.svelte
  Button.test.ts
\`\`\`

Or in a parallel \`__tests__\` directory:

\`\`\`
src/lib/components/
  Counter.svelte
  Button.svelte
  __tests__/
    Counter.test.ts
    Button.test.ts
\`\`\`

Both patterns work. Co-location (first pattern) is more common in the Svelte ecosystem because it keeps related files together and is easier to maintain.

Run tests with:

\`\`\`bash
npx vitest         # Watch mode (re-runs on changes)
npx vitest run     # Single run (CI/CD)
npx vitest --ui    # Visual UI
\`\`\``
		},
		{
			type: 'concept-callout',
			content: 'sveltekit.testing.component-testing'
		},
		{
			type: 'text',
			content: `## Exercise 1: Test a Counter Component

You are given a Counter component with increment, decrement, and reset functionality. Write tests to verify its behavior using Vitest and Testing Library.

**Your task:**
1. Test that the counter renders with the initial count
2. Test that clicking increment increases the count
3. Test that clicking decrement decreases the count`
		},
		{
			type: 'checkpoint',
			content: 'cp-1'
		},
		{
			type: 'text',
			content: `## Testing Edge Cases and Callbacks

Now test the counter's edge cases: the reset button and the \`onchange\` callback prop.

**Task:** Write tests for the reset button returning to the initial count, and verify that the \`onchange\` callback is called with the new count value after each interaction.`
		},
		{
			type: 'checkpoint',
			content: 'cp-2'
		},
		{
			type: 'text',
			content: `## Exercise 2: Test a Todo List Component

Now apply what you have learned to a more complex component. The TodoList component below supports adding, removing, and filtering todo items. Write tests that cover the full user workflow.

The TodoList component uses \`$state\` for the items array and filter text, \`$derived\` for the filtered list, and callback props for notifying parents of changes.

\`\`\`svelte
<!-- TodoList.svelte -->
<script lang="ts">
  interface Todo {
    id: number;
    text: string;
    done: boolean;
  }

  let { initialTodos = [], onchange }: {
    initialTodos?: Todo[];
    onchange?: (todos: Todo[]) => void;
  } = $props();

  let todos = $state<Todo[]>(initialTodos);
  let newText = $state('');
  let filter = $state<'all' | 'active' | 'done'>('all');

  const filteredTodos = $derived(
    filter === 'all' ? todos :
    filter === 'active' ? todos.filter(t => !t.done) :
    todos.filter(t => t.done)
  );

  const remaining = $derived(todos.filter(t => !t.done).length);

  function add() {
    if (!newText.trim()) return;
    todos = [...todos, { id: Date.now(), text: newText.trim(), done: false }];
    newText = '';
    onchange?.(todos);
  }

  function remove(id: number) {
    todos = todos.filter(t => t.id !== id);
    onchange?.(todos);
  }

  function toggle(id: number) {
    todos = todos.map(t => t.id === id ? { ...t, done: !t.done } : t);
    onchange?.(todos);
  }
</script>
\`\`\`

**Your task:** Write tests that verify:
1. Adding a todo via the input and add button
2. Removing a todo by clicking its delete button
3. Filtering between all, active, and done todos
4. The remaining count updates correctly
5. Empty input does not add a todo

Think about how each \`$state\` mutation flows through \`$derived\` to the DOM. Use \`waitFor\` where async updates are involved, and prefer accessible queries (\`getByRole\`, \`getByLabelText\`) over test IDs.`
		},
		{
			type: 'xray-prompt',
			content: `Why does Testing Library recommend querying by role instead of by test ID or CSS class? How does this approach improve both test quality and component accessibility? What are the tradeoffs of testing user-facing behavior vs internal state in Svelte 5 components?`
		},
		{
			type: 'text',
			content: `## Summary

Component testing with Vitest and \`@testing-library/svelte\` verifies that your Svelte 5 components behave correctly from a user's perspective. Svelte's compiled, no-virtual-DOM architecture means tests run against compiled output, and reactive updates are asynchronous -- always await interactions and use \`waitFor\` or \`tick()\` to assert on updated DOM state. Configure Vitest with the \`sveltekit()\` plugin to compile \`.svelte\` files, choose \`jsdom\` or \`happy-dom\` as your DOM environment, and set up \`@testing-library/jest-dom\` for expressive assertions. Test \`$state\` changes through their DOM effects, verify \`$derived\` computations by changing inputs and asserting outputs, and confirm \`$effect\` side effects by observing their observable outcomes. Mock SvelteKit modules (\`$app/navigation\`, \`$app/state\`) and component context (\`getContext\`) to isolate components under test. Use snapshot testing sparingly for structure-sensitive components, and prefer integration-style tests that verify complete user flows (interaction to API call to UI update) for critical paths. Structure tests alongside components, prefer accessible queries, and test behavior rather than implementation details. The result is a test suite that catches regressions, survives refactoring, and runs in milliseconds.`
		}
	],

	starterFiles: [
		{
			name: 'Counter.svelte',
			path: '/src/lib/components/Counter.svelte',
			language: 'svelte',
			content: `<script lang="ts">
  let { initialCount = 0, onchange }: {
    initialCount?: number;
    onchange?: (count: number) => void;
  } = $props();

  let count = $state(initialCount);

  function increment() {
    count++;
    onchange?.(count);
  }

  function decrement() {
    count--;
    onchange?.(count);
  }

  function reset() {
    count = initialCount;
    onchange?.(count);
  }
</script>

<div class="counter">
  <p>Count: {count}</p>
  <button onclick={decrement}>Decrement</button>
  <button onclick={increment}>Increment</button>
  <button onclick={reset}>Reset</button>
</div>`
		},
		{
			name: 'Counter.test.ts',
			path: '/src/lib/components/Counter.test.ts',
			language: 'typescript',
			content: `import { describe, test, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/svelte';
import Counter from './Counter.svelte';

describe('Counter', () => {
  // TODO: Test that counter renders with initial count
  test('renders with default initial count of 0', () => {
    // render(Counter);
    // expect(screen.getByText('Count: 0')).toBeInTheDocument();
  });

  // TODO: Test that clicking increment increases the count
  test('increments count on button click', async () => {
    // render(Counter);
    // const button = screen.getByRole('button', { name: 'Increment' });
    // await fireEvent.click(button);
    // expect ...
  });

  // TODO: Test that clicking decrement decreases the count
  test('decrements count on button click', async () => {

  });

  // TODO: Test that reset returns to initial count
  test('resets to initial count', async () => {

  });

  // TODO: Test that onchange callback is called
  test('calls onchange with new count', async () => {

  });
});`
		}
	],

	solutionFiles: [
		{
			name: 'Counter.svelte',
			path: '/src/lib/components/Counter.svelte',
			language: 'svelte',
			content: `<script lang="ts">
  let { initialCount = 0, onchange }: {
    initialCount?: number;
    onchange?: (count: number) => void;
  } = $props();

  let count = $state(initialCount);

  function increment() {
    count++;
    onchange?.(count);
  }

  function decrement() {
    count--;
    onchange?.(count);
  }

  function reset() {
    count = initialCount;
    onchange?.(count);
  }
</script>

<div class="counter">
  <p>Count: {count}</p>
  <button onclick={decrement}>Decrement</button>
  <button onclick={increment}>Increment</button>
  <button onclick={reset}>Reset</button>
</div>`
		},
		{
			name: 'Counter.test.ts',
			path: '/src/lib/components/Counter.test.ts',
			language: 'typescript',
			content: `import { describe, test, expect, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/svelte';
import Counter from './Counter.svelte';

describe('Counter', () => {
  test('renders with default initial count of 0', () => {
    render(Counter);
    expect(screen.getByText('Count: 0')).toBeInTheDocument();
  });

  test('renders with custom initial count', () => {
    render(Counter, { props: { initialCount: 10 } });
    expect(screen.getByText('Count: 10')).toBeInTheDocument();
  });

  test('increments count on button click', async () => {
    render(Counter, { props: { initialCount: 0 } });
    const button = screen.getByRole('button', { name: 'Increment' });

    await fireEvent.click(button);

    await waitFor(() => {
      expect(screen.getByText('Count: 1')).toBeInTheDocument();
    });
  });

  test('decrements count on button click', async () => {
    render(Counter, { props: { initialCount: 5 } });
    const button = screen.getByRole('button', { name: 'Decrement' });

    await fireEvent.click(button);

    await waitFor(() => {
      expect(screen.getByText('Count: 4')).toBeInTheDocument();
    });
  });

  test('resets to initial count', async () => {
    render(Counter, { props: { initialCount: 3 } });

    const increment = screen.getByRole('button', { name: 'Increment' });
    await fireEvent.click(increment);
    await fireEvent.click(increment);

    await waitFor(() => {
      expect(screen.getByText('Count: 5')).toBeInTheDocument();
    });

    const reset = screen.getByRole('button', { name: 'Reset' });
    await fireEvent.click(reset);

    await waitFor(() => {
      expect(screen.getByText('Count: 3')).toBeInTheDocument();
    });
  });

  test('calls onchange with new count on increment', async () => {
    const handleChange = vi.fn();
    render(Counter, { props: { initialCount: 0, onchange: handleChange } });

    await fireEvent.click(screen.getByRole('button', { name: 'Increment' }));
    expect(handleChange).toHaveBeenCalledWith(1);

    await fireEvent.click(screen.getByRole('button', { name: 'Increment' }));
    expect(handleChange).toHaveBeenCalledWith(2);

    expect(handleChange).toHaveBeenCalledTimes(2);
  });

  test('calls onchange with new count on decrement', async () => {
    const handleChange = vi.fn();
    render(Counter, { props: { initialCount: 5, onchange: handleChange } });

    await fireEvent.click(screen.getByRole('button', { name: 'Decrement' }));
    expect(handleChange).toHaveBeenCalledWith(4);
  });

  test('calls onchange with initial count on reset', async () => {
    const handleChange = vi.fn();
    render(Counter, { props: { initialCount: 3, onchange: handleChange } });

    await fireEvent.click(screen.getByRole('button', { name: 'Increment' }));
    await fireEvent.click(screen.getByRole('button', { name: 'Reset' }));

    expect(handleChange).toHaveBeenLastCalledWith(3);
  });
});`
		}
	],

	checkpoints: [
		{
			id: 'cp-1',
			description: 'Write tests for render, increment, and decrement',
			validation: {
				type: 'code-pattern',
				config: {
					patterns: [
						{ type: 'contains', value: 'render(Counter' },
						{ type: 'contains', value: 'fireEvent.click' },
						{ type: 'contains', value: 'toBeInTheDocument' }
					]
				}
			},
			hints: [
				'Use `render(Counter)` or `render(Counter, { props: { initialCount: 5 } })` to mount the component.',
				'Find the increment button with `screen.getByRole("button", { name: "Increment" })` and click it with `await fireEvent.click(button)`.',
				'After clicking, use `await waitFor(() => { expect(screen.getByText("Count: 1")).toBeInTheDocument(); })` to verify the DOM updated.'
			],
			conceptsTested: ['sveltekit.testing.component-testing']
		},
		{
			id: 'cp-2',
			description: 'Test reset functionality and onchange callback',
			validation: {
				type: 'code-pattern',
				config: {
					patterns: [
						{ type: 'contains', value: 'vi.fn()' },
						{ type: 'contains', value: 'toHaveBeenCalledWith' },
						{ type: 'contains', value: 'Reset' }
					]
				}
			},
			hints: [
				'Create a mock function with `const handleChange = vi.fn()` and pass it as the `onchange` prop.',
				'After clicking increment, assert `expect(handleChange).toHaveBeenCalledWith(1)` to verify the callback received the new count.',
				'For reset, first increment a few times, then click Reset and verify the count text shows the initial value again.'
			],
			conceptsTested: ['sveltekit.testing.vitest-setup']
		}
	]
};
